
CREATE TABLE EVAL_TIP_GESTION
(
    N_ID_TIPO_GESTION NUMBER PRIMARY KEY,
    C_DESCRIPCION VARCHAR2(150),
    N_PESO NUMBER,
    N_ESTADO NUMBER,
    C_USU_REGISTRO VARCHAR2(12),
    D_FEC_REGISTRO DATE
);



CREATE TABLE EVAL_REQ_DETALLE
(
    N_ID_REQ_DETALLE NUMBER PRIMARY KEY,
    N_ID_RQ VARCHAR2(12),
    C_COD_AUTORIZACION VARCHAR2(15),
    D_FEC_TRX DATE,
    N_MTO NUMBER(18,2),
    C_USU_REGISTRO VARCHAR2(12),
    D_FEC_REGISTRO DATE,
    N_ID_TIPO_GESTION NUMBER,
    D_FEC_GESTION DATE,
   CONSTRAINT fk_tipo_gestion FOREIGN KEY (n_id_tipo_gestion) REFERENCES EVAL_TIP_GESTION(N_ID_TIPO_GESTION)
);


INSERT INTO EVAL_TIP_GESTION (N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (1, 'Tipo Gestión 1', 10, 1, 'ADMIN', SYSDATE);

INSERT INTO EVAL_TIP_GESTION (N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (2, 'Tipo Gestión 2', 20, 1, 'ADMIN', SYSDATE);

INSERT INTO EVAL_TIP_GESTION (N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (3, 'Tipo Gestión 3', 30, 1, 'ADMIN', SYSDATE);

INSERT INTO EVAL_TIP_GESTION (N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (4, 'Tipo Gestión 4', 40, 1, 'ADMIN', SYSDATE);

INSERT INTO EVAL_TIP_GESTION (N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (5, 'Tipo Gestión 5', 50, 1, 'ADMIN', SYSDATE);

INSERT INTO EVAL_TIP_GESTION (N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (6, 'Tipo Gestión 6', 60, 1, 'ADMIN', SYSDATE);

-- INSERTs para EVAL_REQ_DETALLE
INSERT INTO EVAL_REQ_DETALLE (N_ID_REQ_DETALLE, N_ID_RQ, C_COD_AUTORIZACION, D_FEC_TRX, N_MTO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (1, '200001', 'T00031', SYSDATE, 145.00, 'ADMIN', SYSDATE);

INSERT INTO EVAL_REQ_DETALLE (N_ID_REQ_DETALLE, N_ID_RQ, C_COD_AUTORIZACION, D_FEC_TRX, N_MTO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (2, '200002', 'T00032', SYSDATE, 135.00, 'ADMIN', SYSDATE);

INSERT INTO EVAL_REQ_DETALLE (N_ID_REQ_DETALLE, N_ID_RQ, C_COD_AUTORIZACION, D_FEC_TRX, N_MTO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (3, '200003', 'T00033', SYSDATE, 240.00, 'ADMIN', SYSDATE);

INSERT INTO EVAL_REQ_DETALLE (N_ID_REQ_DETALLE, N_ID_RQ, C_COD_AUTORIZACION, D_FEC_TRX, N_MTO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (4, '200004', 'T00034', SYSDATE, 280.00, 'ADMIN', SYSDATE);

INSERT INTO EVAL_REQ_DETALLE (N_ID_REQ_DETALLE, N_ID_RQ, C_COD_AUTORIZACION, D_FEC_TRX, N_MTO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (5, '200005', 'T00035', SYSDATE, 120.00, 'ADMIN', SYSDATE);

COMMIT;

--################
CREATE OR REPLACE PACKAGE PKG_EVAL_ASIGNACION AS
    PROCEDURE AsignarTipoGestion;
END PKG_EVAL_ASIGNACION;
/

CREATE OR REPLACE PACKAGE BODY PKG_EVAL_ASIGNACION AS

    PROCEDURE AsignarTipoGestion IS
        CURSOR req_cursor IS
            SELECT N_ID_REQ_DETALLE, N_MTO FROM EVAL_REQ_DETALLE;
        v_id_tipo_gestion NUMBER;
    BEGIN
        FOR req IN req_cursor LOOP
            IF req.N_MTO <= 10 THEN
                v_id_tipo_gestion := 6;
            ELSIF req.N_MTO > 10 AND req.N_MTO <= 35 THEN
                v_id_tipo_gestion := 5;
            ELSIF req.N_MTO > 35 AND req.N_MTO <= 100 THEN
                v_id_tipo_gestion := 4;
            ELSE
                v_id_tipo_gestion := 3;
            END IF;

            UPDATE EVAL_REQ_DETALLE
            SET N_ID_TIPO_GESTION = v_id_tipo_gestion,
                D_FEC_TRX = TRUNC(SYSDATE)  -- Solo la fecha
            WHERE N_ID_REQ_DETALLE = req.N_ID_REQ_DETALLE;
        END LOOP;
        COMMIT;
    END AsignarTipoGestion;

END PKG_EVAL_ASIGNACION;
/